### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-solista#10]
Go to http://mariachisolista.com/ and resize it to phone status. 

Better yet, look at it on your phone and a few other phones. 

What do you notice? 

What would you change? 

Comment here with your answers and use screenshots if necessary. 

Then get to work and make the changes to optimize the site for mobile viewing. 

due:
12-10-15   3p

**Comment by rampage1213** [comment]
Below are images are results of playing around with inspect elements  
<img width="882" alt="screen shot 2015-12-02 at 11 15 42 am" src="https://cloud.githubusercontent.com/assets/7650448/11541350/c004abd8-98e6-11e5-9b25-23898f2657bd.png">
<img width="884" alt="screen shot 2015-12-02 at 11 16 07 am" src="https://cloud.githubusercontent.com/assets/7650448/11541352/c01bdd6c-98e6-11e5-826b-f767d9c7a1fb.png">
<img width="662" alt="screen shot 2015-12-02 at 11 16 22 am" src="https://cloud.githubusercontent.com/assets/7650448/11541353/c021388e-98e6-11e5-99ca-95874252b024.png">
<img width="396" alt="screen shot 2015-12-02 at 11 16 52 am" src="https://cloud.githubusercontent.com/assets/7650448/11541354/c02446e6-98e6-11e5-8914-0d2c9f6fb8c9.png">

A lot of whats making it not responsive is the result of using position relative and manually positioning items. Also using for example width: 300px; instead of using width: auto; and letting it grow with the page. The pic above are mostly removing styles and adding width: auto; the one thing that i couldn't get to work is the controls for the music playing section but i have a good idea on how to fix this site. Getting started on the changes now.

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Good work
