### ISSUE TITLE
Gradient at the top of the bottom content div

### ISSUE THREAD

**Issue by purplyrocky** [EditLLC/client-solista#5]
I can't get the gradient to position behind the bottom content div hence the ugly top black border in order to cover the overlapping gradient.

**Comment by purplyrocky** [comment]
I have tried using the pseudo class .jumbotron:after and .bottom-half:before and I can't get the gradient to position correctly behind the bottom scrolling div, Right now, it is set to #gradient:before because I thought I could make it work if i made a separate div inbetween the jumbotron and scrolling half. It did not work.

**Comment by rodneystrong** [comment]
Just fixed with this commit: https://github.com/EditLLC/client-solista/commit/c02885d071c1afb4025a176d080024d53265c605

Good effort on getting this far with the box-shadow @purplyrocky ! 

The last thing that remained was making sure the parent element for the :before (in this case, #gradient) had to be relatively or absolutely positioned because the child element has an absolute: position property. 

If you look at the code from the about.me page again, you should inspect the parent element of that code that contains the box-shadow and you'll notice that it's got a position: relative on it. 

I also reduced the bottom: -180px position to -20px for better positioning of the shadow, but you would've figured that out once you've seen postion: relative for the parent element.

**Comment by purplyrocky** [comment]
@rodneystrong Thank you so much for helping me with this! I will have to study more about positioning >.<
