### ISSUE TITLE
wonky logo size when resizing

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-solista#9]
here's a short video of how the logo gets morphed when the browser is resized. 

https://drive.google.com/file/d/0BzVFl2mibGTnbFJwb1l3TnJBNnM/view?usp=sharing

please add CSS to make sure the logo doesn't do that. 

i know what code you need to add, but i want you to figure it out. You have 1 day before you're allowed to cry and ask me for help. 

Due date: 
7-10-15 12p

**Comment by purplyrocky** [comment]
shoot! is it okay if i get this done by 7pm today? i didn't see that this was due at noon :(

**Comment by purplyrocky** [comment]
I'm having a hard time trying to figure out exactly what you mean by "wonky". I think i see how the width looks a little squished so i am assuming that's what you mean.  Can you send me what breakpoints you were viewing the "wonky"-ness?
I tried offsetting the column instead of having two columns.
I also tried changing the container to container-fluid. I am thinking of adding a media query, am i at least headed the right direction?
@rodneystrong

**Comment by rodneystrong** [comment]
it just required you to remove the height property on that rule. do that and you can close the issue!

**Comment by purplyrocky** [comment]
done
